import enum

class ErrorCodes(enum.IntEnum):
    # 0–99: General / IO
    ERR_PACK_NOT_FOUND = 0
    ERR_PACK_ENTRY_MISSING = 1

    # 100–199: Format / structure
    ERR_PACK_INVALID_HEADER = 100
    ERR_PACK_VERSION_UNSUPPORTED = 101
    ERR_PACK_SECTION_NOT_ALLOWED = 102
    ERR_PACK_SECTION_UNKNOWN = 103
    ERR_PACK_SECTION_NOT_LOADED = 104

    # 200–299: Security / tamper
    ERR_PACK_SIGNATURE_INVALID = 200
    ERR_PACK_HASH_INVALID = 201
    ERR_PACK_SIGNATURE_MISSING = 202
    ERR_PACK_HASH_MISSING = 203

    # 300 - 399: Corruption
    PACK_CORRUPTED = 300